/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  title: '鸽蛋科技 | For Goodat',
  url: 'https://teaching.vip',
  baseUrl: '/',
  favicon: 'img/favicon.ico',
  organizationName: 'Wangc',
  projectName: 'blog',
  customFields: {

  },
  themeConfig: {
    metadata: [

    ],
    colorMode: {
      defaultMode: 'dark',
      disableSwitch: false,
      respectPrefersColorScheme: false,
    },
    docs: {
      sidebar: {
        hideable: true,
        autoCollapseCategories: false,
      },
      versionPersistence: 'localStorage',
    },
    navbar: {
      logo: {
        alt: 'wangc',
        src: 'svg/teaching-logo-l-1.svg',
        srcDark: 'svg/teaching-logo-l-1.svg',
      },
      hideOnScroll: true,
      items: [
        {
          label: '官网',
          position: 'right',
          to: 'https://teaching.vip/',
        },
        {
          label: '在线演示',
          position: 'right',
          to: 'https://teaching.vip/teaching-demo',
        },
        {
          label: '商业授权',
          position: 'right',
          to: 'https://teaching.vip/pricing',
        },

        {
          type: 'localeDropdown',
          position: 'right',
          dropdownItemsBefore: [],
          dropdownItemsAfter: [],
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: '项目',
          items: [
            {
              label: '官网',
              to: 'https://teaching.vip/',
            },
            {
              label: '开源演示',
              to: 'https://open.teaching.vip/',
            },
          ],
        },
        {
          title: '开源代码',
          items: [
            {
              label: 'Github',
              to: 'https://github.com/open-scratch/teaching-open',
            },
            {
              label: 'Gitee(码云)',
              href: 'https://gitee.com/chengyu2333/teaching-open',
            },
          ],
        },
        {
          title: '更多',
          items: [
            {
              html: '\n                <a href="https://docusaurus.io/zh-CN/" target="_blank" rel="noreferrer noopener">\n                  <img src="/img/buildwith.png" alt="build with docusaurus" width="120" height="50"/>\n                <a/>\n                ',
            },
          ],
        },
      ],
      copyright:
        '\n        <p style="margin-bottom: 0;"><a href="http://beian.miit.gov.cn/">沪ICP备20009532号-4</a></p>\n        <p>Copyright © 2025 - Goodat.Co.Ltd 上海鸽蛋网络科技</p>\n        ',
    },
    algolia: {
      appId: ' ',
      apiKey: ' ',
      indexName: ' ',
      contextualSearch: true,
      searchParameters: {},
      searchPagePath: 'search',
    },
    prism: {
      theme: {
        plain: {
          backgroundColor: 'hsl(220, 13%, 18%)',
          color: 'hsl(220, 14%, 71%)',
          textShadow: '0 1px rgba(0, 0, 0, 0.3)',
        },
        styles: [
          {
            types: ['comment', 'prolog', 'cdata'],
            style: {
              color: 'hsl(220, 10%, 40%)',
            },
          },
          {
            types: ['doctype', 'punctuation', 'entity'],
            style: {
              color: 'hsl(220, 14%, 71%)',
            },
          },
          {
            types: [
              'attr-name',
              'class-name',
              'maybe-class-name',
              'boolean',
              'constant',
              'number',
              'atrule',
            ],
            style: {
              color: 'hsl(29, 54%, 61%)',
            },
          },
          {
            types: ['keyword'],
            style: {
              color: 'hsl(286, 60%, 67%)',
            },
          },
          {
            types: ['property', 'tag', 'symbol', 'deleted', 'important'],
            style: {
              color: 'hsl(355, 65%, 65%)',
            },
          },
          {
            types: ['selector', 'string', 'char', 'builtin', 'inserted', 'regex', 'attr-value'],
            style: {
              color: 'hsl(95, 38%, 62%)',
            },
          },
          {
            types: ['variable', 'operator', 'function'],
            style: {
              color: 'hsl(207, 82%, 66%)',
            },
          },
          {
            types: ['url'],
            style: {
              color: 'hsl(187, 47%, 55%)',
            },
          },
          {
            types: ['deleted'],
            style: {
              textDecorationLine: 'line-through',
            },
          },
          {
            types: ['inserted'],
            style: {
              textDecorationLine: 'underline',
            },
          },
          {
            types: ['italic'],
            style: {
              fontStyle: 'italic',
            },
          },
          {
            types: ['important', 'bold'],
            style: {
              fontWeight: 'bold',
            },
          },
          {
            types: ['important'],
            style: {
              color: 'hsl(220, 14%, 71%)',
            },
          },
        ],
      },
      darkTheme: {
        plain: {
          backgroundColor: 'hsl(220, 13%, 18%)',
          color: 'hsl(220, 14%, 71%)',
          textShadow: '0 1px rgba(0, 0, 0, 0.3)',
        },
        styles: [
          {
            types: ['comment', 'prolog', 'cdata'],
            style: {
              color: 'hsl(220, 10%, 40%)',
            },
          },
          {
            types: ['doctype', 'punctuation', 'entity'],
            style: {
              color: 'hsl(220, 14%, 71%)',
            },
          },
          {
            types: [
              'attr-name',
              'class-name',
              'maybe-class-name',
              'boolean',
              'constant',
              'number',
              'atrule',
            ],
            style: {
              color: 'hsl(29, 54%, 61%)',
            },
          },
          {
            types: ['keyword'],
            style: {
              color: 'hsl(286, 60%, 67%)',
            },
          },
          {
            types: ['property', 'tag', 'symbol', 'deleted', 'important'],
            style: {
              color: 'hsl(355, 65%, 65%)',
            },
          },
          {
            types: ['selector', 'string', 'char', 'builtin', 'inserted', 'regex', 'attr-value'],
            style: {
              color: 'hsl(95, 38%, 62%)',
            },
          },
          {
            types: ['variable', 'operator', 'function'],
            style: {
              color: 'hsl(207, 82%, 66%)',
            },
          },
          {
            types: ['url'],
            style: {
              color: 'hsl(187, 47%, 55%)',
            },
          },
          {
            types: ['deleted'],
            style: {
              textDecorationLine: 'line-through',
            },
          },
          {
            types: ['inserted'],
            style: {
              textDecorationLine: 'underline',
            },
          },
          {
            types: ['italic'],
            style: {
              fontStyle: 'italic',
            },
          },
          {
            types: ['important', 'bold'],
            style: {
              fontWeight: 'bold',
            },
          },
          {
            types: ['important'],
            style: {
              color: 'hsl(220, 14%, 71%)',
            },
          },
        ],
      },
      additionalLanguages: [
        'bash',
        'json',
        'java',
        'python',
        'php',
        'graphql',
        'rust',
        'toml',
        'protobuf',
      ],
      defaultLanguage: 'javascript',
      magicComments: [
        {
          className: 'theme-code-block-highlighted-line',
          line: 'highlight-next-line',
          block: {
            start: 'highlight-start',
            end: 'highlight-end',
          },
        },
        {
          className: 'code-block-error-line',
          line: 'This will error',
        },
      ],
    },
    giscus: {
      repo: 'kuizuo/blog',
      repoId: 'MDEwOlJlcG9zaXRvcnkzOTc2MjU2MTI=',
      category: 'General',
      categoryId: 'DIC_kwDOF7NJDM4CPK95',
      theme: 'light',
      darkTheme: 'dark_dimmed',
    },
    tableOfContents: {
      minHeadingLevel: 2,
      maxHeadingLevel: 4,
    },
    liveCodeBlock: {
      playgroundPosition: 'top',
    },
    zoom: {
      selector: '.markdown :not(em) > img',
      background: {
        light: 'rgb(255, 255, 255)',
        dark: 'rgb(50, 50, 50)',
      },
    },
    blog: {
      sidebar: {
        groupByYear: true,
      },
    },
  },
  presets: [
    [
      'classic',
      {
        //   docs: {
        //    path: 'docs',
        //    sidebarPath: 'sidebars.ts',
        //   },
        blog: false,
        theme: {
          customCss: ['./src/css/custom.scss'],
        },
        sitemap: {
          priority: 0.5,
        },
        gtag: {
          trackingID: 'G-S4SD5NXWXF',
          anonymizeIP: true,
        },
        debug: true,
      },
    ],
  ],
  plugins: [
     'docusaurus-plugin-sass',
    [
      '@docusaurus/plugin-pwa',
      {
        debug: true,
        offlineModeActivationStrategies: ['appInstalled', 'standalone', 'queryString'],
        pwaHead: [
          {
            tagName: 'link',
            rel: 'icon',
            href: '/img/logo.png',
          },
          {
            tagName: 'link',
            rel: 'manifest',
            href: '/manifest.json',
          },
          {
            tagName: 'meta',
            name: 'theme-color',
            content: '#12affa',
          },
        ],
      },
    ],
    [
      './src/plugin/plugin-content-blog',
      {
        path: 'blog',
        editLocalizedFiles: false,
        blogDescription: '学而不思则罔 思而不学则殆',
        blogSidebarCount: 10,
        blogSidebarTitle: 'Blogs',
        postsPerPage: 10,
        showReadingTime: true,
        feedOptions: {
          type: 'all',
          title: 'Wangc',
          copyright:
            'Copyright © 2025 Wangc Built with Docusaurus.<p><a href="http://beian.miit.gov.cn/" class="footer_lin">京ICP备2022016509号-1</a></p>',
        },
      },
    ],
  ],
  headTags: [
    {
      tagName: 'meta',
      attributes: {
        name: 'description',
        content: 'wangc的个人博客',
      },
    },
  ],
  stylesheets: [
    'https://cdn.jsdelivr.net/npm/misans@4.0.0/lib/Normal/MiSans-Normal.min.css',
    'https://cdn.jsdelivr.net/npm/misans@4.0.0/lib/Normal/MiSans-Semibold.min.css',
  ],
  i18n: {
    defaultLocale: 'zh-CN',
    locales: ['zh-CN'],
    localeConfigs: {
      en: {
        htmlLang: 'en-GB',
        direction: 'ltr',
      },
    },
    path: 'i18n',
  },
  baseUrlIssueBanner: true,
  future: {
    experimental_faster: {
      swcJsLoader: false,
      swcJsMinimizer: false,
      swcHtmlMinimizer: false,
      lightningCssMinimizer: false,
      mdxCrossCompilerCache: false,
      rspackBundler: false,
    },
    experimental_storage: {
      type: 'localStorage',
      namespace: false,
    },
    experimental_router: 'browser',
  },
  onBrokenLinks: 'throw',
  onBrokenAnchors: 'warn',
  onBrokenMarkdownLinks: 'warn',
  onDuplicateRoutes: 'warn',
  staticDirectories: ['static'],
  themes: [],
  scripts: [],
  clientModules: [],
  tagline: '',
  titleDelimiter: '|',
  noIndex: false,
  markdown: {
    format: 'mdx',
    mermaid: false,
    mdx1Compat: {
      comments: true,
      admonitions: true,
      headingIds: true,
    },
    anchors: {
      maintainCase: false,
    },
  },
}
